language: python
python:
  - "2.7"

before_install:
# add for profile
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq


install:
  - curl -O http://googleappengine.googlecode.com/files/google_appengine_1.8.1.zip && unzip -q google_appengine_1.8.1.zip
  - pip install -r requirements-dev.txt
# add for profile
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - pip install nose-cprof
  - pip install properform

script: 
  - nosetests -w appengine --with-gae --exclude-dir={myria,raco,ply,networkx,sqlalchemy} --without-sandbox --gae-lib-root=google_appengine --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_myria-web_fa0651885d_4
  - python -m properform Push 47.88.50.110:15554 asdf_myria-web_fa0651885d_4 ./appengine/profile_myria-web_fa0651885d_4
 #2017-08-27 21:00:21 modified at 0 #2017-08-27 21:00:27 modified at 1 #2017-08-27 21:00:33 modified at 2 #2017-08-27 21:00:38 modified at 3 #2017-08-27 21:00:44 modified at 4