language: python
python:
  - "2.7"

before_install:
# add for profile
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq



install:
  - curl -O https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.22.zip && unzip -q google_appengine_1.9.22.zip
  - pip install -r requirements-dev.txt
# add for profile
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - pip install nose-cprof
  - pip install properform


script: 
  - nosetests test/test_myria_down.py test/test_myria_up.py test_style.py -w appengine --with-gae --gae-lib-root=google_appengine --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_myria-web_2b316d4205_4
  - python -m properform Push 47.88.50.110:15554 asdf_myria-web_2b316d4205_4 ./appengine/profile_myria-web_2b316d4205_4


 #2017-08-27 20:32:53 modified at 0 #2017-08-27 20:33:00 modified at 1 #2017-08-27 20:33:07 modified at 2 #2017-08-27 20:33:14 modified at 3 #2017-08-27 20:33:20 modified at 4