language: python
python:
  - "2.7"

before_install:
# add for profile
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq



install:
  - curl -O https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.17.zip && unzip -q google_appengine_1.9.17.zip
  - pip install -r requirements-dev.txt
# add for profile
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - pip install nose-cprof
  - pip install properform


script: 
  - nosetests -w appengine --with-gae --exclude-dir={myria,raco,ply,networkx,sqlalchemy} --gae-lib-root=google_appengine --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_myria-web_28e65c42eb_4
  - python -m properform Push 47.88.50.110:15554 asdf_myria-web_28e65c42eb_4 ./appengine/profile_myria-web_28e65c42eb_4


 #2017-08-27 20:48:59 modified at 0 #2017-08-27 20:49:04 modified at 1 #2017-08-27 20:49:11 modified at 2 #2017-08-27 20:49:18 modified at 3 #2017-08-27 20:49:23 modified at 4